name: enterprise-search
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - nodejs=22
  - pip:
    - fastapi>=0.104.1
    - uvicorn[standard]>=0.24.0
    - httpx>=0.25.2
    - python-jose[cryptography]>=3.3.0
    - python-multipart>=0.0.6
    - pydantic[email]>=2.4.2
    - pydantic-settings>=2.0.3
    - python-dotenv>=1.0.0
    - elasticsearch>=8.18.0
    - faker>=18.0.0
    - pytest>=7.4.3
    - pytest-asyncio>=0.21.1
    - black>=23.11.0
    - flake8>=6.1.0
    - mypy>=1.7.0
