// src/components/UI/SummaryHeader.tsx
import React from 'react';

interface SummaryHeaderProps {
  initialDocument?: any;
  searchResults: any[];
  summaryType: 'quick' | 'comprehensive';
  setSummaryType: (type: 'quick' | 'comprehensive') => void;
  onClose: () => void;
}

const SummaryHeader: React.FC<SummaryHeaderProps> = ({
  initialDocument,
  searchResults,
  summaryType,
  setSummaryType,
  onClose
}) => {
  return (
    <div className="bg-gradient-to-r from-blue-600 via-purple-600 to-blue-700 text-white p-6 relative overflow-hidden">
      {/* Background Pattern */}
      <div className="absolute inset-0 opacity-10">
        <div className="absolute inset-0" style={{
          backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.3'%3E%3Ccircle cx='7' cy='7' r='1'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`
        }}></div>
      </div>
      
      <div className="flex justify-between items-start relative z-10">
        <div className="flex-1">
          <div className="flex items-center gap-3 mb-2">
            <div className="bg-white/20 p-2 rounded-lg">
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
            </div>
            <h2 className="text-2xl font-bold">📄 AI Summary</h2>
          </div>
          <p className="text-blue-100 mt-1 text-lg">
            {initialDocument 
              ? `✨ Summary of: ${initialDocument.title}`
              : `📊 Summary of ${searchResults.length} search results`}
          </p>
          <div className="mt-1 text-sm text-blue-200">
            🤖 Generated by Enterprise AI • {new Date().toLocaleDateString()}
          </div>
        </div>
        <button
          onClick={onClose}
          className="text-white hover:text-gray-200 transition-all duration-200 hover:bg-white/10 p-2 rounded-lg"
          title="Close Summary"
        >
          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      
      {/* Enhanced Summary Type Toggle */}
      <div className="flex gap-2 mt-6 relative z-10">
        <button
          onClick={() => setSummaryType('quick')}
          className={`px-6 py-3 rounded-lg transition-all duration-200 flex items-center gap-2 ${
            summaryType === 'quick' 
              ? 'bg-white text-blue-600 shadow-lg transform scale-105' 
              : 'bg-blue-500/50 text-white hover:bg-blue-400/70 hover:scale-102'
          }`}
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
          </svg>
          Quick Summary
        </button>
        <button
          onClick={() => setSummaryType('comprehensive')}
          className={`px-6 py-3 rounded-lg transition-all duration-200 flex items-center gap-2 ${
            summaryType === 'comprehensive' 
              ? 'bg-white text-blue-600 shadow-lg transform scale-105' 
              : 'bg-blue-500/50 text-white hover:bg-blue-400/70 hover:scale-102'
          }`}
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
          </svg>
          Comprehensive
        </button>
      </div>
    </div>
  );
};

export default SummaryHeader;
